#Esto se aplica a todas las config
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
name:
  value: alibou
spring:
  cloud:
    config:
      override-system-properties: false
#Para usare Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
