CREATE TABLE IF NOT EXISTS usuario(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    APELLIDO VARCHAR(255) NOT NULL,
    EDAD INTEGER,
    EMAIL VARCHAR(255),
    NOMBRE VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(255)
);